types = []

restaurant_data = [['german', "Esther's German Saloon", '$$$', '3', '22 Teutonic Ave.'],
                   ['japanese', 'Robatayaki Hachi','$$$$', '4', '8 Hawthorne Ln.'],
                   ['vegetarian', 'BBQ Tofu Paradise', '$$', '1', '22A King West'],
                   ['french', 'Le Bateau Rouge', '$$$$$', '4', '2 South Park Dr.'],
                   ['african', 'Khartoum Khartoum', '$$$', '2', '1566 Maple Rd.'],
                   ['american', "Sally's Diner", '$$$$', '3', '96 College Blvd.'],
                   ['barbecue', 'Saucy Piggy', '$$$', '2', '623 Industrial Rd.'],
                   ['czech', 'Czech Point', '$', '4', '5567 Queen-Mary Rd'],
                   ['german', 'Der Speisewagen', '$$$', '5', '402 College Blvd.'],
                   ['chinese', 'Beijing Express', '$$', '4', '38 Teutonic Ave.'],
                   ['thai', 'Satay Village', '$$$$', '2', '12 High St.'],
                   ['mexican', 'Cancun', '$$$', '3', '2030 Maple Rd.'],
                   ['indian', 'Curry Up', '$$$$', '5', '455 University'],
                   ['african', 'Carthage', '$$', '1', '59 Court Terrace'],
                   ['american', 'Burgerama', '$$$$$', '4', '456 University'],
                   ['barbecue', 'Three Little Pigs', '$$$', '2', '12 Summer Court'],
                   ['czech', 'Little Prague', '$$$$', '3', '44 Park Ave'],
                   ['german', 'Kohl Haus', '$$$', '2', '3421 Queen-Mary Rd'],
                   ['chinese', "Dragon's Tail", '$', '4', '8 Jasmine Rd.'],
                   ['thai', 'Hit Me Baby One More Thai', '$$$', '5', '12 Jasmine Rd.'],
                   ['mexican', 'The Whole Tamale', '$$', '4', '401 University'],
                   ['indian', 'Birmingham Bhangra', '$$$$', '2', '992 Riddick St.'],
                   ['mexican', 'Taqueria', '$$$', '3', '12 North Circle Dr.'],
                   ['mexican', "Pedro's", '$$$$', '5', '5521 Alameda'],
                   ['chinese', 'Super Wonton Express', '$$', '1', '223 Milliways Ave'],
                   ['indian', 'Naan Sequitur', '$$$$$', '4', '"Unit 12'],
                   ['japanese', 'Sakura', '$$$', '2', '"Unit 18'],
                   ['chinese', 'Shandong Lu', '$$$$', '3', '335 University'],
                   ['indian', 'Curry Galore', '$$$', '2', '56 Park Ave'],
                   ['cafe', 'North by Northwest', '$', '4', '201 University'],
                   ['cafe', 'Full of Beans', '$$$', '5', '498 College Ave.'],
                   ['cafe', "Tropical Jeeve's Cafe", '$$', '4', '550 Milliways Ave'],
                   ['cafe', 'Zardoz Cafe', '$$$$', '2', '6202 Alameda'],
                   ['pizza', 'Angular Pizza', '$', '5', '2232 King St.'],
                   ['pizza', 'Flavia', '$$$$', '5', '401 Riddick St.'],
                   ['pizza', "Luigi's House of Pies", '$$', '1', '5 Garcia Ave.'],
                   ['pizza', 'Thick and Thin', '$$$$$', '4', '832 Dominican Ave.'],
                   ['pizza', 'When in Rome', '$$$', '2', '234 Valencia St.'],
                   ['pizza', 'Pizza 76', '$$$$', '3', '76 Market St.'],
                   ['italian', 'Party Pasta', '$$$$$', '2', '70 E Main St'],
                   ['italian', 'Pasta Palace', '$$$', '4', '12 E Main St'],
                   ['vegetarian', 'Veggie Heaven', '$$$$', '4', '69 E 146th St']]

# Creates a list that will grow with any new types of restaurants without having to manually add them
# this allows for the program to be more dynamic and not have to be updated every time a new restaurant is added
for restaurant in restaurant_data:
    if restaurant[0] not in types:
        types.append(restaurant[0])